/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin/seo'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminReelsRouteImport } from './routes/_authenticated/admin/reels'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPoliciesRouteImport } from './routes/_authenticated/admin/policies'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAccountIdRouteImport } from './routes/_authenticated/account/$id'
import { Route as AuthenticatedAdminInventoryIndexRouteImport } from './routes/_authenticated/admin/inventory.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAdminProductsNewRouteImport } from './routes/_authenticated/admin/products.new'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated/admin/orders.$id'
import { Route as AuthenticatedAdminInventorySuppliersRouteImport } from './routes/_authenticated/admin/inventory.suppliers'
import { Route as AuthenticatedAdminInventoryPurchasesRouteImport } from './routes/_authenticated/admin/inventory.purchases'
import { Route as AuthenticatedAdminInventoryProductsRouteImport } from './routes/_authenticated/admin/inventory.products'
import { Route as AuthenticatedAdminInventoryLowStockRouteImport } from './routes/_authenticated/admin/inventory.low-stock'
import { Route as AuthenticatedAdminInventoryHistoryRouteImport } from './routes/_authenticated/admin/inventory.history'
import { Route as AuthenticatedAdminInventoryAdjustRouteImport } from './routes/_authenticated/admin/inventory.adjust'
import { Route as AuthenticatedAdminCustomersAnalyticsRouteImport } from './routes/_authenticated/admin/customers.analytics'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin/customers.$id'
import { Route as AuthenticatedAdminCategoriesNewRouteImport } from './routes/_authenticated/admin/categories.new'
import { Route as AuthenticatedAdminCategoriesIdRouteImport } from './routes/_authenticated/admin/categories.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReelsRoute = AuthenticatedAdminReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPoliciesRoute =
  AuthenticatedAdminPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAccountIdRoute = AuthenticatedAccountIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAccountRoute,
} as any)
const AuthenticatedAdminInventoryIndexRoute =
  AuthenticatedAdminInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminProductsNewRoute =
  AuthenticatedAdminProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAdminInventorySuppliersRoute =
  AuthenticatedAdminInventorySuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryPurchasesRoute =
  AuthenticatedAdminInventoryPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryProductsRoute =
  AuthenticatedAdminInventoryProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryLowStockRoute =
  AuthenticatedAdminInventoryLowStockRouteImport.update({
    id: '/low-stock',
    path: '/low-stock',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryHistoryRoute =
  AuthenticatedAdminInventoryHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminInventoryAdjustRoute =
  AuthenticatedAdminInventoryAdjustRouteImport.update({
    id: '/adjust',
    path: '/adjust',
    getParentRoute: () => AuthenticatedAdminInventoryRoute,
  } as any)
const AuthenticatedAdminCustomersAnalyticsRoute =
  AuthenticatedAdminCustomersAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminCategoriesNewRoute =
  AuthenticatedAdminCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)
const AuthenticatedAdminCategoriesIdRoute =
  AuthenticatedAdminCategoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/account/$id': typeof AuthenticatedAccountIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers/analytics': typeof AuthenticatedAdminCustomersAnalyticsRoute
  '/admin/inventory/adjust': typeof AuthenticatedAdminInventoryAdjustRoute
  '/admin/inventory/history': typeof AuthenticatedAdminInventoryHistoryRoute
  '/admin/inventory/low-stock': typeof AuthenticatedAdminInventoryLowStockRoute
  '/admin/inventory/products': typeof AuthenticatedAdminInventoryProductsRoute
  '/admin/inventory/purchases': typeof AuthenticatedAdminInventoryPurchasesRoute
  '/admin/inventory/suppliers': typeof AuthenticatedAdminInventorySuppliersRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/inventory/': typeof AuthenticatedAdminInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/account/$id': typeof AuthenticatedAccountIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRoute
  '/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/customers/analytics': typeof AuthenticatedAdminCustomersAnalyticsRoute
  '/admin/inventory/adjust': typeof AuthenticatedAdminInventoryAdjustRoute
  '/admin/inventory/history': typeof AuthenticatedAdminInventoryHistoryRoute
  '/admin/inventory/low-stock': typeof AuthenticatedAdminInventoryLowStockRoute
  '/admin/inventory/products': typeof AuthenticatedAdminInventoryProductsRoute
  '/admin/inventory/purchases': typeof AuthenticatedAdminInventoryPurchasesRoute
  '/admin/inventory/suppliers': typeof AuthenticatedAdminInventorySuppliersRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/account/$id': typeof AuthenticatedAccountIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRouteWithChildren
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRouteWithChildren
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/reels': typeof AuthenticatedAdminReelsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/categories/$id': typeof AuthenticatedAdminCategoriesIdRoute
  '/_authenticated/admin/categories/new': typeof AuthenticatedAdminCategoriesNewRoute
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/customers/analytics': typeof AuthenticatedAdminCustomersAnalyticsRoute
  '/_authenticated/admin/inventory/adjust': typeof AuthenticatedAdminInventoryAdjustRoute
  '/_authenticated/admin/inventory/history': typeof AuthenticatedAdminInventoryHistoryRoute
  '/_authenticated/admin/inventory/low-stock': typeof AuthenticatedAdminInventoryLowStockRoute
  '/_authenticated/admin/inventory/products': typeof AuthenticatedAdminInventoryProductsRoute
  '/_authenticated/admin/inventory/purchases': typeof AuthenticatedAdminInventoryPurchasesRoute
  '/_authenticated/admin/inventory/suppliers': typeof AuthenticatedAdminInventorySuppliersRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/products/new': typeof AuthenticatedAdminProductsNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/inventory/': typeof AuthenticatedAdminInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/reset-password'
    | '/wishlist'
    | '/admin'
    | '/account'
    | '/policies/$slug'
    | '/products/$slug'
    | '/products/'
    | '/account/$id'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/reels'
    | '/admin/reports'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/categories/$id'
    | '/admin/categories/new'
    | '/admin/customers/$id'
    | '/admin/customers/analytics'
    | '/admin/inventory/adjust'
    | '/admin/inventory/history'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/products'
    | '/admin/inventory/purchases'
    | '/admin/inventory/suppliers'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/lovable/email/queue/process'
    | '/admin/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/reset-password'
    | '/wishlist'
    | '/account'
    | '/policies/$slug'
    | '/products/$slug'
    | '/products'
    | '/account/$id'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/policies'
    | '/admin/products'
    | '/admin/reels'
    | '/admin/reports'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/categories/$id'
    | '/admin/categories/new'
    | '/admin/customers/$id'
    | '/admin/customers/analytics'
    | '/admin/inventory/adjust'
    | '/admin/inventory/history'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/products'
    | '/admin/inventory/purchases'
    | '/admin/inventory/suppliers'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/lovable/email/queue/process'
    | '/admin/inventory'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/reset-password'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/policies/$slug'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/account/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/policies'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reels'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/categories/$id'
    | '/_authenticated/admin/categories/new'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/customers/analytics'
    | '/_authenticated/admin/inventory/adjust'
    | '/_authenticated/admin/inventory/history'
    | '/_authenticated/admin/inventory/low-stock'
    | '/_authenticated/admin/inventory/products'
    | '/_authenticated/admin/inventory/purchases'
    | '/_authenticated/admin/inventory/suppliers'
    | '/_authenticated/admin/orders/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/products/new'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WishlistRoute: typeof WishlistRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reels': {
      id: '/_authenticated/admin/reels'
      path: '/reels'
      fullPath: '/admin/reels'
      preLoaderRoute: typeof AuthenticatedAdminReelsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/policies': {
      id: '/_authenticated/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/account/$id': {
      id: '/_authenticated/account/$id'
      path: '/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AuthenticatedAccountIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/inventory/': {
      id: '/_authenticated/admin/inventory/'
      path: '/'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AuthenticatedAdminInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/products/new': {
      id: '/_authenticated/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AuthenticatedAdminProductsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/admin/inventory/suppliers': {
      id: '/_authenticated/admin/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/admin/inventory/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminInventorySuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/purchases': {
      id: '/_authenticated/admin/inventory/purchases'
      path: '/purchases'
      fullPath: '/admin/inventory/purchases'
      preLoaderRoute: typeof AuthenticatedAdminInventoryPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/products': {
      id: '/_authenticated/admin/inventory/products'
      path: '/products'
      fullPath: '/admin/inventory/products'
      preLoaderRoute: typeof AuthenticatedAdminInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/low-stock': {
      id: '/_authenticated/admin/inventory/low-stock'
      path: '/low-stock'
      fullPath: '/admin/inventory/low-stock'
      preLoaderRoute: typeof AuthenticatedAdminInventoryLowStockRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/history': {
      id: '/_authenticated/admin/inventory/history'
      path: '/history'
      fullPath: '/admin/inventory/history'
      preLoaderRoute: typeof AuthenticatedAdminInventoryHistoryRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/inventory/adjust': {
      id: '/_authenticated/admin/inventory/adjust'
      path: '/adjust'
      fullPath: '/admin/inventory/adjust'
      preLoaderRoute: typeof AuthenticatedAdminInventoryAdjustRouteImport
      parentRoute: typeof AuthenticatedAdminInventoryRoute
    }
    '/_authenticated/admin/customers/analytics': {
      id: '/_authenticated/admin/customers/analytics'
      path: '/analytics'
      fullPath: '/admin/customers/analytics'
      preLoaderRoute: typeof AuthenticatedAdminCustomersAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/categories/new': {
      id: '/_authenticated/admin/categories/new'
      path: '/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
    '/_authenticated/admin/categories/$id': {
      id: '/_authenticated/admin/categories/$id'
      path: '/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCategoriesRoute
    }
  }
}

interface AuthenticatedAdminCategoriesRouteChildren {
  AuthenticatedAdminCategoriesIdRoute: typeof AuthenticatedAdminCategoriesIdRoute
  AuthenticatedAdminCategoriesNewRoute: typeof AuthenticatedAdminCategoriesNewRoute
}

const AuthenticatedAdminCategoriesRouteChildren: AuthenticatedAdminCategoriesRouteChildren =
  {
    AuthenticatedAdminCategoriesIdRoute: AuthenticatedAdminCategoriesIdRoute,
    AuthenticatedAdminCategoriesNewRoute: AuthenticatedAdminCategoriesNewRoute,
  }

const AuthenticatedAdminCategoriesRouteWithChildren =
  AuthenticatedAdminCategoriesRoute._addFileChildren(
    AuthenticatedAdminCategoriesRouteChildren,
  )

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminCustomersAnalyticsRoute: typeof AuthenticatedAdminCustomersAnalyticsRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
    AuthenticatedAdminCustomersAnalyticsRoute:
      AuthenticatedAdminCustomersAnalyticsRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminInventoryRouteChildren {
  AuthenticatedAdminInventoryAdjustRoute: typeof AuthenticatedAdminInventoryAdjustRoute
  AuthenticatedAdminInventoryHistoryRoute: typeof AuthenticatedAdminInventoryHistoryRoute
  AuthenticatedAdminInventoryLowStockRoute: typeof AuthenticatedAdminInventoryLowStockRoute
  AuthenticatedAdminInventoryProductsRoute: typeof AuthenticatedAdminInventoryProductsRoute
  AuthenticatedAdminInventoryPurchasesRoute: typeof AuthenticatedAdminInventoryPurchasesRoute
  AuthenticatedAdminInventorySuppliersRoute: typeof AuthenticatedAdminInventorySuppliersRoute
  AuthenticatedAdminInventoryIndexRoute: typeof AuthenticatedAdminInventoryIndexRoute
}

const AuthenticatedAdminInventoryRouteChildren: AuthenticatedAdminInventoryRouteChildren =
  {
    AuthenticatedAdminInventoryAdjustRoute:
      AuthenticatedAdminInventoryAdjustRoute,
    AuthenticatedAdminInventoryHistoryRoute:
      AuthenticatedAdminInventoryHistoryRoute,
    AuthenticatedAdminInventoryLowStockRoute:
      AuthenticatedAdminInventoryLowStockRoute,
    AuthenticatedAdminInventoryProductsRoute:
      AuthenticatedAdminInventoryProductsRoute,
    AuthenticatedAdminInventoryPurchasesRoute:
      AuthenticatedAdminInventoryPurchasesRoute,
    AuthenticatedAdminInventorySuppliersRoute:
      AuthenticatedAdminInventorySuppliersRoute,
    AuthenticatedAdminInventoryIndexRoute:
      AuthenticatedAdminInventoryIndexRoute,
  }

const AuthenticatedAdminInventoryRouteWithChildren =
  AuthenticatedAdminInventoryRoute._addFileChildren(
    AuthenticatedAdminInventoryRouteChildren,
  )

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsNewRoute: typeof AuthenticatedAdminProductsNewRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsNewRoute: AuthenticatedAdminProductsNewRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRouteWithChildren
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRouteWithChildren
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPoliciesRoute: typeof AuthenticatedAdminPoliciesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminReelsRoute: typeof AuthenticatedAdminReelsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminCategoriesRoute:
      AuthenticatedAdminCategoriesRouteWithChildren,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminCustomersRoute:
      AuthenticatedAdminCustomersRouteWithChildren,
    AuthenticatedAdminInventoryRoute:
      AuthenticatedAdminInventoryRouteWithChildren,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
    AuthenticatedAdminPoliciesRoute: AuthenticatedAdminPoliciesRoute,
    AuthenticatedAdminProductsRoute:
      AuthenticatedAdminProductsRouteWithChildren,
    AuthenticatedAdminReelsRoute: AuthenticatedAdminReelsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountIdRoute: typeof AuthenticatedAccountIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountIdRoute: AuthenticatedAccountIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WishlistRoute: WishlistRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
